import mongoose, { Schema, Document, Types } from "mongoose";
import { BudgetType } from "./Budget";

export interface ITransaction extends Document {
  userId: Types.ObjectId;
  budgetId: Types.ObjectId;
  budgetType: BudgetType;
  name: string;
  category: string;
  amount: number;
  date: Date;
  source: "manual" | "agent" | "subscription";
  transcript?: string;
  // Set when this transaction was auto-generated by a subscription.
  subscriptionId?: Types.ObjectId;
}

const transactionSchema = new Schema<ITransaction>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    budgetId: { type: Schema.Types.ObjectId, ref: "Budget", required: true, index: true },
    budgetType: { type: String, enum: ["monthly", "yearly"], required: true },
    name: { type: String, required: true, trim: true },
    category: { type: String, required: true, trim: true },
    amount: { type: Number, required: true, min: 0 },
    date: { type: Date, required: true, default: Date.now },
    source: {
      type: String,
      enum: ["manual", "agent", "subscription"],
      required: true,
      default: "manual",
    },
    transcript: { type: String },
    subscriptionId: { type: Schema.Types.ObjectId, ref: "Subscription", default: null, index: true },
  },
  { timestamps: true }
);

export const Transaction = mongoose.model<ITransaction>("Transaction", transactionSchema);
